pipeline {
    
    agent any

    stages {

        stage('Maven package') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network devops
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('librairie-back') {
                    withSonarQubeEnv('SonarQube') {
                        sh "mvn clean verify sonar:sonar -Dsonar.projectKey=librairie-back -Dsonar.projectName='librairie-back'"
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('librairie-back') {
                    sh 'docker build -t ajc/projetLibrairie:boot .'
                }
            }
        }

        //stage('Docker Deploy') {
        //    steps {
        //        dir('./docker') {
        //            sh 'docker compose up -d --no-deps --build boot'
        //        }
        //    }
        //}
    }
}